In [58]:
import numpy as np

In [59]:
mat = np.array([[1, 2], [3, 4]])
vec = np.array([1, 2])

mat.shape  # (2, 2)
vec.shape  # (2,)

(2,)

In [60]:
mat[0, 0] # 1 - top left element
mat[1, 1] # 4 - bottom right element

mat[:, 0] # array([1, 3])

array([1, 3])

In [62]:
# 3 x 3 identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
# transpose of matrix - switchign rows and columns
mat.transpose()


array([[1, 3],
       [2, 4]])

In [64]:
mat.T

array([[1, 3],
       [2, 4]])

In [65]:
#Trace gives the sum of the diagonal elements
A = np.array([[1, 2], [3, 4]])
A.trace()  

5

In [66]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 1], [0, 1]])
I = np.eye(2)

In [67]:
# Matrix multiplication

In [68]:
A @ B

array([[-1,  3],
       [-3,  7]])

In [69]:
#Components multiplied together

In [70]:
A * B

array([[-1,  2],
       [ 0,  4]])

In [52]:
A @ I 

array([[1., 2.],
       [3., 4.]])

In [53]:
#How to find inverses
from numpy import linalg

linalg.inv(A)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [54]:
Ainv = linalg.inv(A)
Ainv @ A

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [55]:
A @ Ainv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [57]:
#Determinant - either this week or next week we will cover this.
linalg.det(A)


-2.0000000000000004