This is a list with the following numbers in it: 1, 2, 3, 4, 5, 10

In [1]:
list = [1, 2, 3, 4, 5, 10]

In [2]:
list

[1, 2, 3, 4, 5, 10]

The len() function will tell you the length of strings and other objects (like lists). It will not work on numbers by themselves.


In [15]:
len(list)

6

Find difference between the last element of the list and the 3rd element of the list.
We begin our count indexed at 0, and -1 is the last digit.

In [16]:
difference = list[-1]-list[2]

In [67]:
print(difference)

7


NumPy is a fundamental package in Python. Normally you will often access NumPy functions and you will transform data into NumPy arrays to build machine learning models.

In [2]:
#import library NumPy and create an alias np to call our functions on
import numpy as np

An array is an immutable object which organizes data points in rows and columns. It is immutable because it stores all items in an individual object or strip of memory - everytime you change the array, in the background Python is creating a copy of the array and storing a new object with a new reference point.

In [65]:
arr = np.array([1, 2, 3, 4]) 
arr

array([1, 2, 3, 4])

In [66]:
arr[0]  
arr[2]  

3

In [68]:
arr[::2] 

array([1, 3])

In [20]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [21]:
a = [4,5,6]

In [22]:
array_a=np.array(a)
array_a

array([4, 5, 6])

In [23]:
array_b = np.array([7,8,9])
array_b

array([7, 8, 9])

In [27]:
array_c= np.array([[1, 2, 3],[4, 5, 6]])
array_c

array([[1, 2, 3],
       [4, 5, 6]])

The shape function will tell you the parameters of the array - how many rows and columns.

In [28]:
np.shape(array_c)

(2, 3)

In [29]:
array_c*10

array([[10, 20, 30],
       [40, 50, 60]])

In [30]:
lista=[1,2,3]
listb=[4,5,6]

In [32]:
array_d=np.array([lista,listb])
array_d

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
array_d[1,1] = 100
array_d

array([[  1,   2,   3],
       [  4, 100,   6]])

In [40]:
array_e=array_d

In [41]:
array_d

array([[  1,   2,   3],
       [  4, 100,   6]])

In [44]:
array_d*array_a

array([[  4,  10,  18],
       [ 16, 500,  36]])

You can also use the reshape() function to change the shape of an array.

In [46]:
x1 = np.arange(4)
x2 = x1.reshape(4,1)
x2

array([[0],
       [1],
       [2],
       [3]])

In [47]:
x1

array([0, 1, 2, 3])

In [52]:
x2.shape

(4, 1)

To create an array of all 1s or all 0s - you can do this with the ones() or zeros() functions.

In [51]:
x3=np.ones(5)
x3

array([1., 1., 1., 1., 1.])

In [53]:
x3.shape

(5,)

Tensor can sometimes be used in AI. Below is an example of one.

In [57]:
a_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
a_3d[0,1,2]

6

In [59]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, -3, 1])
a + b # array([2, 2, 0, 5])
a - b # array([0, 2, 6, 3])
a * b # array([ 1, 0, -9, 4])
b / a # array([ 1. , 0. , -1. , 0.25])
b**a # array([1, 0, -27, 1])

a = np.array([1, 2, 3, 4])
new = 2*a
print(new)
# [2, 4, 6, 8]

[2 4 6 8]


In [5]:
#This is an example from our lecture notes... 
from numpy import linalg

A = np.array([[1, -2, 1], [0, 2, -8], [-4, 5, 9]])
b = np.array([0, 8, -9])

linalg.solve(A, b)  # array([ 29., 16., 3.])

array([29., 16.,  3.])