# Eigenvalues and Eigenvectors

In [2]:
import numpy as np
from numpy import linalg

In [5]:
A = np.array([[3, -1, 4], [-1, 0, -1], [4, -1, 2]])

v, B = linalg.eig(A)

i = 0  # first eigenvalue/eigenvector pair
lambda0 = v[i]
print(lambda0)
print(B)
print(v)

6.823156164525974
[[ 0.73271846 -0.65131465  0.19726352]
 [-0.20260301  0.06794858  0.97690072]
 [ 0.64967352  0.75575937  0.08217113]]
[ 6.82315616 -1.53711415 -0.28604201]


In [54]:
x0 = B[:, i]  # ith column of B
print(x0)

[ 0.73271846 -0.20260301  0.64967352]


In [55]:
lhs = A @ x0
rhs = lambda0*x0
linalg.norm(lhs - rhs)  

6.2842938400131246e-15

# Singular Value Decomposition

In [56]:
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
# SVD
U, d, VT = svd(A)
print(U)
print(d)
print(VT)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
