In [1]:
import pandas as pd

In [2]:
sales = {'account': ['Jones LLC', 'Alpha Co', 'Blue Inc'],
         'Jan': [150, 200, 50],
         'Feb': [200, 210, 90],
         'Mar': [140, 215, 95]}
df_sales = pd.DataFrame.from_dict(sales)
df_sales.drop(df_sales.index[2])
print(df_sales)

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95


In [3]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr2[~sr2.isin(sr1)])

2     6
3     8
4    10
dtype: int64


In [4]:
import numpy as np

In [5]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [11]:
np.concatenate([b, a], axis=0)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr1[~sr1.isin(sr2)])

0    1
2    3
4    5
dtype: int64


In [13]:
series1 = pd.Series([1, 3, 5, 8, 10, 11, 15])
print(series1.diff().diff().tolist())

[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


In [14]:
sales = {'account': ['Jones LLC', 'Alpha Co', 'Blue Inc'],
         'Jan': [150, 200, 50],
         'Feb': [200, 210, 90],
         'Mar': [140, 215, 95]}
df_sales = pd.DataFrame.from_dict(sales)
df_sales.drop(df_sales.index[2])
print(df_sales)

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95


In [15]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr2[sr2.isin(sr1)])

0    2
1    4
dtype: int64


In [16]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(b, a))

[6 7 8 9]


In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [18]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.intersect1d(b, a))

[5]


In [19]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [20]:
series1 = pd.Series([1, 3, 5, 8, 10, 11, 15])
print(series1.diff().tolist())

[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]


In [21]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr1[sr1.isin(sr2)])

1    2
3    4
dtype: int64


In [22]:
a = np.array([[1,2,3],[0,1,4]])
print (a.size)

6


In [23]:
s1 = pd.Series(['a', 'b', 'c'])
s2 = pd.Series([1,2,3])
df = pd.concat([s1, s2], axis=0)
print(df)

0    a
1    b
2    c
0    1
1    2
2    3
dtype: object


In [25]:
pd.Series(dict({"key": "value"}))

key    value
dtype: object