### Instructions 

####  1. rename this notebook to yourname_studentid.ipynb
####  2. submit your work to DC-connect (midterm-test) folder

####  3. You are only allowed to use the following libraries
####  Numpy, Pandas


#### -----------------------------------------------------------------------------------
####   Sairaj Udayshankar <placeholder>

####   100865420 <placeholder>

In [1]:
# import numpy & pandas
import numpy as np
import pandas as pd

In [3]:
# 1 point
# create a variable 'my_name' and assign your name to it
# e.g my_name = "john doe"
my_name = "sairaj udayshankar"

In [6]:
# 2 points
# find all the unique characters of my name and assign to a list called my_list
# e.g. my_list = all unique lower case characters of my name (It is Ok to have 'space' character included in the list ) 
my_list = []
for character in my_name:
    if my_list.count(character) > 0:
        continue
    else:
        my_list.append(character)

my_list

['s', 'a', 'i', 'r', 'j', ' ', 'u', 'd', 'y', 'h', 'n', 'k']

In [9]:
# 2 points
#find  all the ascii value associated with characters of my_list and assign it to my_list_ascii
# please use 'ord' method to convert character to ascii
# e.g my_list = ['j','o','h','n', ' ', 'd','o','e'] 
# my_list_ascii = [90, 91,92, .....]
my_list_ascii = []
for character in my_list:
    my_list_ascii.append(ord(character))

print(my_list)
print(my_list_ascii)

['s', 'a', 'i', 'r', 'j', ' ', 'u', 'd', 'y', 'h', 'n', 'k']
[115, 97, 105, 114, 106, 32, 117, 100, 121, 104, 110, 107]


In [11]:
#  1 points
# create a numpy array ranging from 0 to 50
# e.g  y = numpy array (0, 50)
y = np.arange(51)

y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
#  5 points
# without using the python loop methods (for, while), change the sign of elements indexing from 5 to 10 of the y array to negative
# e.g output should be 0, 1,2,3,4,-5,-6,-7,-8,-9,10,11,12, ......., 50
y[5:10] *= -1

y

array([ 0,  1,  2,  3,  4, -5, -6, -7, -8, -9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
# 1 points

#create a variable name my_id and assign your student_id
# e.g my_id = "1001233445"
my_id = "100865420"

In [19]:
# 1 points
#create a numpy array using my_id variable (No hard coded inputs e.g [1,0,0,1, ...])
my_id_list = np.array(list(my_id), dtype=int)

my_id_list

array([1, 0, 0, 8, 6, 5, 4, 2, 0])

In [21]:
# 2 points
# create a numpy array (w) using the following function
# w = x**2 - 0.25x +0.5 (where x = my_id) (here, my_id is a numpy array)
w = my_id_list**2 - 0.25*my_id_list + 0.5

w

array([ 1.25,  0.5 ,  0.5 , 62.5 , 35.  , 24.25, 15.5 ,  4.  ,  0.5 ])

In [22]:
# 2 points
# calculate the element-wise multiplication of w and my_id (w*my_id)
# e.g
# z = w(i) * my_id(i) where  i in length of (my_id)
w * my_id_list

array([  1.25,   0.  ,   0.  , 500.  , 210.  , 121.25,  62.  ,   8.  ,
         0.  ])

In [25]:
# 1 points
# calculate the dot-product from previous cell (e.g sum (w*my_id)) and assign it to a variable name 'my_total'
# e.g my_total = sum of  (w*my_id)
my_total = sum(w * my_id_list)

my_total

902.5

In [26]:
# 1 point
# convert the my_total to an integer. if the my_total is smaller that 100, add 100 to the my_total
# e.g 
# if my_total < 100:
#    my_total += 100
my_total = int(my_total)

my_total

902

In [32]:
# 8 points
# find all the prime numbers from 2 to  my_total (make sure my_total is an integer)
# 
def find_prime(num):
    prime = True
    for divisor in np.arange(2, num):
        if num % divisor == 0:
            prime = False
            return False
        else:
            continue
    if prime == True:
        return True

prime_numbers = []
for num in np.arange(2, my_total):
    if find_prime(num):
        prime_numbers.append(num)

prime_numbers

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229,
 233,
 239,
 241,
 251,
 257,
 263,
 269,
 271,
 277,
 281,
 283,
 293,
 307,
 311,
 313,
 317,
 331,
 337,
 347,
 349,
 353,
 359,
 367,
 373,
 379,
 383,
 389,
 397,
 401,
 409,
 419,
 421,
 431,
 433,
 439,
 443,
 449,
 457,
 461,
 463,
 467,
 479,
 487,
 491,
 499,
 503,
 509,
 521,
 523,
 541,
 547,
 557,
 563,
 569,
 571,
 577,
 587,
 593,
 599,
 601,
 607,
 613,
 617,
 619,
 631,
 641,
 643,
 647,
 653,
 659,
 661,
 673,
 677,
 683,
 691,
 701,
 709,
 719,
 727,
 733,
 739,
 743,
 751,
 757,
 761,
 769,
 773,
 787,
 797,
 809,
 811,
 821,
 823,
 827,
 829,
 839,
 853,
 857,
 859,
 863,
 877,
 881,
 883,
 887]

In [53]:
# 13 points

# write a program to implement KNN algorithm to classify data into two classes (class 0 and 1). 
# You can use Numpy and Python standard libraries only
# please use the absolute value to calculate the distance (Manhattan)
# harness:
# points = {0:[(1,2), (1.1,.5), (1.3,0.7), (1.2, 0.6)], 1:[(7,8), (9,11), (12,8), (13,9), (9,9)]}
# test_point = [2,3]

### Harness ####
#  result = my_knn(points, test_point, k=3)
# output : test_point belongs to class 0

points = {0:[(1,2), (1.1,.5), (1.3,0.7), (1.2, 0.6)], 1:[(7,8), (9,11), (12,8), (13,9), (9,9)]}
test_point = [2,3]

def find_distance(pointA, pointB):
    return (abs(pointA[0] - pointB[0]) + abs(pointA[1] - pointB[1]))

def my_knn(points, test_point, k=3):
    points_class_0 = points[0]
    points_class_1 = points[1]

    distance_class_0 = []
    distance_class_1 = []

    for point in points_class_0:
        distance_class_0.append(("0", find_distance(point, test_point)))

    for point in points_class_1:
        distance_class_1.append(("1", find_distance(point, test_point)))

    distances = distance_class_0 + distance_class_1
    distances.sort(key=lambda x:x[1])

    class_0 = []
    class_1 = []

    for item in distances[0:k]:
        if item[0] == "0":
            class_0.append(item)
        else:
            class_1.append(item)
    
    if len(class_0) > len(class_1):
        print("test_point belongs to class 0")
    else:
        print("test_point belongs to class 1")

my_knn(points, test_point, k=3)

test_point belongs to class 0
