In [2]:
import numpy as np

In [3]:
x = [20, 30, 40]
type(x)

list

In [5]:
_x = np.array(x)
_x

array([20, 30, 40])

In [6]:
_x[0]

20

In [7]:
x = [1, 2, 3, "hello"]
_x = np.array(x)
_x

array(['1', '2', '3', 'hello'], dtype='<U11')

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [12]:
print(a.ndim)
print(a2.ndim)

2
3


In [13]:
a.dtype

dtype('int32')

In [14]:
_x.dtype

dtype('<U11')

In [15]:
a = np.array([1, 2, 3, "hello"], dtype="float")

ValueError: could not convert string to float: 'hello'

In [16]:
a1 = np.array(["dog", "cat", "elephant", "monkey"])
print(a1)

['dog' 'cat' 'elephant' 'monkey']


In [17]:
a3 = np.array([1.1, 2.1, 3.1])
print(a3.dtype)

newa3 = a3.astype('i')
newa3

float64


array([1, 2, 3], dtype=int32)

In [20]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a1[0][1])
print(a1[0,1])

2
2


In [21]:
a2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
a2[0, 1, 2]

6

In [22]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[2:5])
print(a[::2])

[3 4 5]
[1 3 5]


In [24]:
a[-3:-1]

array([4, 5])

In [25]:
a1 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
print(a1[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [26]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

n1 = np.array(l1)
n2 = np.array(l2)

n1 * n2

array([ 4, 10, 18])

In [27]:
np.sum(n1 * n2)

32

In [28]:
2*n1

array([2, 4, 6])

In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [30]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr1.shape)
newarr1 = arr1.reshape(4, 3)
print(newarr1)
print(newarr1.shape)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [37]:
arr1.reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [40]:
a1 = np.array([1, 2, 3, 4, 5, 1, 2, 3, 1, 21, 45, 22, 1, 1, 3])

In [41]:
a1.reshape(3, -1)

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  1, 21],
       [45, 22,  1,  1,  3]])

In [42]:
a2 = np.array([[1, 2], [1, 2]])
a2.reshape(-1)

array([1, 2, 1, 2])

In [43]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
def func(num):
    return (num ** 2) - 2 * num

print(np.arange(1, 21))

print(func(np.arange(1, 21)))

func(np.arange(1, 21)).sum()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ -1   0   3   8  15  24  35  48  63  80  99 120 143 168 195 224 255 288
 323 360]


2450

In [54]:
x = np.arange(1, 21)
(x ** 2 - 2*x).sum()

2450