In [9]:
import numpy as np
from numpy import linalg

Question 28 - b

In [4]:
A = np.array([[1, 1/2, 1/3], [1/2, 1/3, 1/4], [1/3, 1/4, 1/5]])
B = np.array([[1, 0.33, 0.2], [0.33, 0.2, 0.15], [0.2, 0.15, 0.11]])

In [5]:
A

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])

In [6]:
B

array([[1.  , 0.33, 0.2 ],
       [0.33, 0.2 , 0.15],
       [0.2 , 0.15, 0.11]])

In [7]:
A @ B

array([[1.23166667, 0.48      , 0.31166667],
       [0.66      , 0.26916667, 0.1775    ],
       [0.45583333, 0.19      , 0.12616667]])

Question 29

In [10]:
A = np.array([[1, 0, 0], [-1, 2, 0], [-2, -1, 1]])
linalg.inv(A)

array([[ 1. , -0. , -0. ],
       [ 0.5,  0.5,  0. ],
       [ 2.5,  0.5,  1. ]])